# Adopt version 2 syntax:
#   https://docs.docker.com/compose/compose-file/#/versioning
version: '2'

#volumes:
#  database_data:
#    driver: local

services:
  ###########################
  # Setup the Database (MySQL) container
  ###########################
  database:
    image: mysql:5.7
    container_name: api-db
    working_dir: /application
    ports:
    - 3302:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: api
      MYSQL_USER: ian
      MYSQL_PASSWORD: cmius

  ###########################
  # Setup the PHP container
  ###########################
  php:
    build: ./docker/php/
    container_name: api-php
    working_dir: /application
    expose:
    - 9000
    volumes:
    - .:/application
    links:
    - database

  ###########################
  # Setup the Nginx container
  ###########################
  webserver:
    image: nginx:latest
    container_name: api-webserver
    working_dir: /application
    ports:
    - 6195:80
    volumes:
    - .:/application
    - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    volumes_from:
    - php
    links:
    - php
